### ISSUE TITLE
cannot use SqlDataProvider as data

### ISSUE THREAD

**Issue by mikk150** [Sibilino/yii2-dygraphswidget#2] opened 2015-11-23 15:30 UTC

**Comment by Sibilino** [comment] 2015-11-27 07:50
Hi, I just added support for SqlDataProvider. Can you test using "dev-master" version and see if the problem is solved before I make a new release?

Thanks

**Comment by Sibilino** [comment] 2015-11-30 08:47
Fixed on latest release.

**Closed as completed by Sibilino** 2015-11-30 08:47 UTC
